config/routes.rb
Rails.application.routes.draw do

  root to:"category#index"
  resources :category, only: %i( index create  update destroy) do
    resources :list, only: %i( create  update destroy)
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
   has_many :lists, dependent: :destroy
   validates :name , presence: true ,length: { minimum: 1, maximum: 50}
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :category
  validates :name, presence: true ,length: {minimum:1,maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController



  def index
    @categories = Category.all
    @category = Category.new
    @list = @category.lists
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_index_path
    else
      @list = List.new
      @categories = Category.all
      render :index
    end
  end


  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to category_index_path
    else
      @list = List.new
      @categories = Category.all
      render :index
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to category_index_path
    else
      @categories = Category.all
      render :index
    end
  end

  private
        def category_params
            params.require(:category).permit(:name,lists_attributes: [:name] )
        end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def new
    @list = List.new
    @category = Category.find_by(id: params[:category_id])
  end

  def create
    category = Category.find(params[:category_id])
    list = List.new(list_params)
    list.category_id = category.id
    list.save
    redirect_to category_index_path
  end

  def edit
  end

  def show
  end

  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to category_index_path
  end


  def destroy
    List.find(params[:id]).destroy
    redirect_to category_index_path
  end
    private

    def list_params
      params.require(:list).permit(:name,:caption,:category_id,:done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/category/edit.html.erb
<div class="categoryeditPage">
    <div class="container">
        <%= form_with model: @category, url: {action: :update},html:{class:'categoryForm'}, local: true do |f| %>
            <% if @category.errors.any? %>
                 <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
            <% end %>
            <%= f.label :name %>
            <%= f.text_field :name,class:"form-control categoryName",placeholder:"カテゴリ名" %>
            <div class="text-center"><%= f.submit "編集する",class:"submitBtn" %></div>
        <% end %>
    </div>
</div>

app/views/category/index.html.erb
<% if @category.errors.any? %>
      <%= @category.errors.count %>errors prohibited this obj from being saved:
      <% @category.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
<% end %>


<div class="categoryList row flex-nowrap mb-6">
<% @categories.each do |category| %>
  <% if category.errors.any? %>
        <%= category.errors.count %>errors prohibited this obj from being saved:
        <% category.errors.full_messages.each do |message| %>
      <%= message %>
      <% end %>
  <% end %>
    <div class="col-4">
      <div class="category-box scolor pb-3">
        <div class="category-name-box mcolor col-10">
          <p class="category-name">
            <%= category.name %>
          </p>
        </div>
            <!--d-flexで横並び、mtでmargin-top -->
          <div class="category-links d-flex  mt-2   justify-content-around">
              <div class="categoryEdit mcolor col-4 rounded text-center pt-1 pb-1">
                <a class=" text-decoration-none fcolor" data-bs-toggle="collapse" href="#collapseEditCategory_<%= category.id%>" role="button" aria-expanded="false" aria-controls="collapseEditCategory_<%= category.id%>">
                  <i class="fas fa-file-pen"></i>  更新
                </a>
              </div>
              <div class="categoryDestroy mcolor col-4 rounded text-center pt-1 pb-1">
                <%= link_to  category_path(category),method: :delete,class:"text-white text-decoration-none" do %>
                  <i class="fas fa-trash-can"></i> 削除
                <% end %>
              </div>
          </div>
          <div class="text-center">
            <%= form_with model: category, method: :patch,class:"collapse  mt-2 mb-1",id:"collapseEditCategory_#{category.id}" do |f| %>
              <%= f.text_area :name,rows:"2",placeholder: "カテゴリーを編集",class:"col-10" %>
              <br>
              <%= f.submit "編集"  %>
            <% end %>
          </div>
          <div class="mcolor col-10 mt-2 mb-2 mx-auto rounded text-white text-center pt-1 pb-1">
            <a class="text-decoration-none text-white" data-bs-toggle="collapse" href="#collapseCreateToDo_<%= category.id %>" role="button" aria-expanded="false" aria-controls="collapseCreateToDo_<%= category.id %>">
              <i class="fa-solid fa-square-plus"></i>  TODO 追加
            </a>
          </div>
          <div class="text-center">

            <%= form_with model: [category,List.new] , url: category_list_index_path(category,@list) ,local: true,class:"collapse",id:"collapseCreateToDo_#{category.id}" do |f| %>
              <%= f.text_area :name, rows: '2', placeholder: "TODOを追加",class:"col-10"  %>
              <br>
              <%= f.submit "追加"  %>
            <% end %>
          </div>
          <div class="todolists mcolor rounded col-10 mx-auto mt-2 pt-2 pb-2 ">
          <ul class="text-white">
            <table>
              <tbody>
                  <tr>
                    <td class="custom-control custom-checkbox col-10 ">
                      <% category.lists.each do |list| %>
                        <%= form_with model: [category,list] do |f| %>
                            <%= f.check_box :done,:as => :boolean %>
                            <%= f.label list.name ,class:"col-8" %>
                            <div class="d-flex ms-2">
                              <a class="text-white" data-bs-toggle="collapse" href="#collapseEditList_<%= list.id %>" role="button" aria-expanded="false" aria-controls="collapseEditList">
                                <i class="fas fa-file-pen"></i>
                              </a>
                              <%= link_to category_list_path(category,list),method: :delete,class:"text-white" do %>
                                <i class="fas fa-trash-can pe-1"></i>
                              <% end %>
                              <div class="collapse" , id="collapseEditList_<%=list.id%>">
                                <%= form_with model: [category,list],class:"col-12 mb-3" do |f| %>
                                  <%= f.text_field :name,class:"form-control categoryName col-12 mt-2 mb-2",placeholder:"TODOを更新" %>
                                  <div class="text-center"><%= f.submit "編集する",class:"submitBtn" %></div>
                                <% end %>
                              </div>
                            </div>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>

              </tbody>
            </table>
          </ul>

        </div>
      </div>
    </div>
<% end %>

</div>

app/views/category/new.html.erb
<div class="newCategory">
  <div class="container">
    <%= form_with model: @category, url: { action: :create }, class: "new_category", local: true do |f| %>
      <% if @category.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :category %>
      <%= f.text_field :name, autofocus: true, class: "form-control categoryName", placeholder: "カテゴリ名" %>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/03fb6268b4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  </head>

  <body>
    <header class = "mcolor fixed-top">
      <div class="container">
        <div class="header">
          <nav class="nav d-flex justify-content-between">
            <div class = "navbar-brand fcolor">todolist</div>
            <div class="scolor rounded h-75 mt-2">
              <a data-bs-toggle="collapse" class="text-decoration-none text-dark ps-2 pe-2 align-middle" href="#collapseCreateCategory" role="button" aria-expanded="false" aria-controls="collapseCreateCategory">
                カテゴリー追加
              </a>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <div class="container mb-5">
      <div class="newCategory">
        <%= form_with model: @category, url: { action: :create }, class: "new_category collapse",id:"collapseCreateCategory", local: true do |f| %>
          <% if @category.errors.any? %>
            <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
          <% end %>
          <%= f.label :category %>
          <%= f.text_field :name, autofocus: true, class: "form-control categoryName", placeholder: "カテゴリ名" %>
          <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/list/destroy.html.erb
<h1>List#destroy</h1>
<p>Find me in app/views/list/destroy.html.erb</p>

app/views/list/edit.html.erb
<h1>List#edit</h1>
<p>Find me in app/views/list/edit.html.erb</p>

app/views/list/new.html.erb
    <% if @list.errors.any? %>
        <%= @list.errors.count %>errors prohibited this obj from being saved:
        <% @list.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
    <% end %>
<div class="newList">
  <div class="container">
    <%= form_with model: [@categoey,@list], url: { action: :create }, class: "new_list", local: true do |f| %>
    <%= f.hidden_field :category_id, value: @list.category %>

      <%= f.label :ToDo %>
      <%= f.text_field :ToDo, autofocus: true, class: "form-control ListName", placeholder: "To Do を入力" %>

      <%= f.label :memo %>
      <%= f.text_field :caption, autofocus: true, class: "form-control ListCaption", placeholder: "メモを入力" %>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/list/show.html.erb
<h1>List#show</h1>
<p>Find me in app/views/list/show.html.erb</p>